name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master   

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install OpenSSL
      run: brew install libressl
    - name: Install Libxml2
      run: brew install libxml2 && brew link --force libxml2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file web.Dockerfile --tag sanderrouk/rt-parser:$(date +%s)