name: Swift

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master   

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Libxml2
      run: brew install libxml2 && brew link --force libxml2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
